
version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file: .env
    environment:
      - GUNICORN_ACCESS_LOGFILE=/dev/null
      - PGADMIN_DEFAULT_EMAIL=$PG_ADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PG_ADMIN_PASS
    depends_on:
      - postgres
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin'
    ports:
      - '15432:80'
    logging:
      driver: 'none'

volumes:
  pg_data:
  pgadmin_data:
